---
- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Copy nginx config
  copy:
    src: ../../../../nginx/yii2.conf
    dest: /etc/nginx/sites-available/yii2.conf

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/yii2.conf
    dest: /etc/nginx/sites-enabled/yii2.conf
    state: link
    force: true

- name: Force remove default NGINX site config
  command: rm -f /etc/nginx/sites-available/default
  args:
    warn: false

- name: Force remove default NGINX site symlink
  command: rm -f /etc/nginx/sites-enabled/default
  args:
    warn: false

- name: Reload NGINX to apply new config
  service:
    name: nginx
    state: reloaded

- name: Restart nginx
  service:
    name: nginx
    state: restarted
